/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArduinoSerial */

#ifndef _Included_ArduinoSerial
#define _Included_ArduinoSerial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArduinoSerial
 * Method:    readTemperature
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArduinoSerial_readTemperature
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
